# These are all the default values as an example - except the email, no default for that.
# The CLI args and env vars always take precedence over config file.

debug = false

[user]
email = "sample@email.com"
priv_key_path = "~/.ssh/id_rsa"
pub_key_path = "~/.ssh/id_rsa.pub"

[instance]
url = "http://localhost:8080"

[daemon]
ip = "0.0.0.0"
port = 8080

[database]
path = "./tmp"
value_path = ""